version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_TCP_PORT: 3310
    ports:
      - "3310:3310"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
